package com.example.demo.dao;

import com.example.demo.model.Role;
import java.util.List;

public interface RoleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated
	 */
	Role selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated
	 */
	List<Role> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Role record);

	List<Role> findUserRole(String account);
}