package com.example.demo.dao;

import com.example.demo.model.UserRole;
import java.util.List;

public interface UserRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbg.generated
	 */
	int insert(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbg.generated
	 */
	List<UserRole> selectAll();
}